### ISSUE TITLE
When optim is not enabled add the parcels without sequence at the end of the round

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#154] opened 2016-05-11 05:39 UTC
If the optimisation is not enable and sequence provided in the announcement. URBANTZ should add at the end of the round the parcels without sequence.

**Comment by Justinuz** [comment] 2016-05-19 15:46
Duplicate of issue #165

**Closed as completed by Justinuz** 2016-05-19 15:46 UTC
Labels: duplicate, enhancement, Web app
